com.course.blog.adminui/Controllers/ArticleController.cs
using com.course.blog.adminui.Helpers;
using com.course.blog.adminui.Models;
using com.course.blog.entities.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using X.PagedList;

namespace com.course.blog.adminui.Controllers
{
    public class ArticleController : BaseController
    {
        private readonly DbBlog _context;
        private readonly IWebHostEnvironment _environment;
        public ArticleController(DbBlog context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public IActionResult ArticleProcess()
        {
            ViewBag.Categories = _context.Categories.Where(c => c.IsActive).Select(s => new SelectListItem { Text = s.Detail, Value = s.CategoryId.ToString() });

            ViewBag.SubCategories = _context.SubCategories.Where(s => s.CategoryId < 0).Select(s => new SelectListItem { Text = s.Detail, Value = s.CategoryId.ToString() });

            return View();
        }

        public IActionResult Articles(ArticleViewModel model)
        {
            ViewBag.Categories = _context.Categories.Where(c => c.IsActive).Select(s => new SelectListItem { Text = s.Detail, Value = s.CategoryId.ToString() });

            ViewBag.SubCategories = _context.SubCategories.Where(c => c.IsActive && c.CategoryId == model.CategoryId).Select(s => new SelectListItem { Text = s.Detail, Value = s.SubCategoryId.ToString() });

            model.Articles = _context.Articles.Where(a => model.SubCategoryId == null || a.SubCategoryId == model.SubCategoryId).ToPagedList(model.Page ?? 1, 20);

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("ArticlePartial", model);
            }
            else
            {
                ViewBag.Articles = model;
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult SaveArticle(Article article)
        {
            var user = HttpContext.Session.Get<User>("User");

            article.ArticleId = Guid.NewGuid();
            article.UserId = user.UserId;
            article.IsActive = true;
            article.SaveDate = DateTime.Now;
            article.ReadCount = 0;

            _context.Articles.Add(article);

            return Json(_context.SaveChanges() > 0);
        }

        [HttpPost]
        public JsonResult GetArticle(Guid id)
        {
            if (_context.Articles.Any(a => a.ArticleId == id))
            {
                var candidate = _context.Articles.Find(id);

                return Json(new
                {
                    articleId = candidate.ArticleId,
                    categoryId = candidate.SubCategory.CategoryId,
                    subcategoryId = candidate.SubCategoryId,
                    subject = candidate.Subject,
                    shortDetail = candidate.ShortDetail,
                    tags = candidate.Tags,
                    detail = candidate.Detail,
                });
            }
            else
            {
                return Json(null);
            }
        }

        [HttpPost]
        public JsonResult UpdateArticle(Guid id, Article article)
        {
            if (_context.Articles.Any(a => a.ArticleId == id))
            {
                var candidate = _context.Articles.Find(id);

                candidate.SubCategoryId = article.SubCategoryId;
                candidate.Subject = article.Subject;
                candidate.ShortDetail = article.ShortDetail;
                candidate.Tags = article.Tags;
                candidate.Detail = article.Detail;
                candidate.Detail = article.Detail;

                candidate.SaveDate = DateTime.Now;

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult ChangeStatus(Guid id)
        {
            if (_context.Articles.Any(a => a.ArticleId == id))
            {
                var candidate = _context.Articles.Find(id);

                candidate.IsActive = !candidate.IsActive;
                candidate.SaveDate = DateTime.Now;

                _context.SaveChanges();

                return Json(candidate.IsActive);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult GetSubCategories(int categoryId)
        {
            return Json(_context.SubCategories.Where(s => s.IsActive && s.CategoryId == categoryId).Select(s => new { text = s.Detail, id = s.SubCategoryId }));
        }

        [HttpPost]
        public JsonResult UploadCover(IFormFile file)
        {
            var fileType = Path.GetExtension(file.FileName);

            if (fileType == ".jpg" || fileType == ".jpeg" || fileType == ".png" || fileType == ".bmp")
            {
                var fileName = Path.ChangeExtension(Path.GetRandomFileName(), fileType);

                var filePath = $"{_environment.WebRootPath}/images/{fileName}";

                using (var stream = System.IO.File.Create(filePath))
                {
                    file.CopyTo(stream);
                }

                var id = Guid.Parse(Request.Form["articleId"]);

                var candidate = _context.Articles.Find(id);
                candidate.CoverPhoto = fileName;

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }
    }
}

com.course.blog.adminui/Controllers/CategoryController.cs
using com.course.blog.adminui.Models;
using com.course.blog.entities.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace com.course.blog.adminui.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly DbBlog _context;
        public CategoryController(DbBlog context)
        {
            _context = context;
        }

        public IActionResult CategoryProcess()
        {
            return View();
        }

        public IActionResult Categories(CategoryViewModel model)
        {
            model.Categories = _context.Categories.ToPagedList(model.Page ?? 1, 20);

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("CategoryPartial", model);
            }
            else
            {
                ViewBag.Categories = model;
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult SaveCategory(string categoryName)
        {
            if (!_context.Categories.Any(c => c.Detail == categoryName))
            {
                var category = new Category
                {
                    Detail = categoryName,
                    SaveDate = DateTime.Now,
                    IsActive = true
                };

                _context.Categories.Add(category);

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult GetCategory(int id)
        {
            if (_context.Categories.Any(c => c.CategoryId == id))
            {
                var candidate = _context.Categories.Find(id);

                return Json(candidate);
            }
            else
            {
                return Json(null);
            }
        }

        [HttpPost]
        public JsonResult UpdateCategory(int id,string categoryName)
        {
            if (_context.Categories.Any(c => c.CategoryId == id))
            {
                var candidate = _context.Categories.Find(id);

                candidate.Detail = categoryName;
                candidate.SaveDate = DateTime.Now;

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            if (_context.Categories.Any(c => c.CategoryId == id))
            {
                var candidate = _context.Categories.Find(id);

                candidate.IsActive = !candidate.IsActive;
                candidate.SaveDate = DateTime.Now;

                _context.SaveChanges();

                return Json(candidate.IsActive);
            }
            else
            {
                return Json(false);
            }
        }
    }
}

com.course.blog.adminui/Controllers/SubCategoryController.cs
using com.course.blog.adminui.Models;
using com.course.blog.entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace com.course.blog.adminui.Controllers
{
    public class SubCategoryController : BaseController
    {
        private readonly DbBlog _context;
        public SubCategoryController(DbBlog context)
        {
            _context = context;
        }
        public IActionResult SubCategoryProcess()
        {
            ViewBag.Categories = _context.Categories.Where(c => c.IsActive).Select(s => new SelectListItem { Text = s.Detail, Value = s.CategoryId.ToString() });

            return View();
        }

        public ActionResult SubCategories(SubCategoryViewModel model)
        {
            ViewBag.Categories = _context.Categories.Where(c => c.IsActive).Select(s => new SelectListItem { Text = s.Detail, Value = s.CategoryId.ToString() });

            model.SubCategories = _context.SubCategories.Where(s => model.CategoryId == null || s.CategoryId == model.CategoryId).ToPagedList(model.Page ?? 1, 20);

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("SubCategoryPartial", model);
            }
            else
            {
                ViewBag.SubCategories = model;
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult SaveSubCategory(int categoryId, string subCategoryName)
        {
            if (!_context.SubCategories.Any(c => c.Detail == subCategoryName))
            {
                var candidate = new SubCategory
                {
                    CategoryId = categoryId,
                    Detail = subCategoryName,
                    SaveDate = DateTime.Now,
                    IsActive = true
                };

                _context.SubCategories.Add(candidate);

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult GetSubCategory(int id)
        {
            if (_context.SubCategories.Any(c => c.SubCategoryId == id))
            {
                var candidate = _context.SubCategories.Find(id);

                return Json(new { categoryId = candidate.CategoryId, subCategoryName = candidate.Detail });
            }
            else
            {
                return Json(null);
            }
        }

        [HttpPost]
        public JsonResult UpdateSubCategory(int id, int categoryId, string subCategoryName)
        {
            if (_context.SubCategories.Any(c => c.SubCategoryId == id))
            {
                var candidate = _context.SubCategories.Find(id);

                candidate.CategoryId = categoryId;
                candidate.Detail = subCategoryName;
                candidate.SaveDate = DateTime.Now;

                return Json(_context.SaveChanges() > 0);
            }
            else
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            if (_context.SubCategories.Any(c => c.CategoryId == id))
            {
                var candidate = _context.SubCategories.Find(id);

                candidate.IsActive = !candidate.IsActive;
                candidate.SaveDate = DateTime.Now;

                _context.SaveChanges();

                return Json(candidate.IsActive);
            }
            else
            {
                return Json(false);
            }
        }
    }
}

com.course.blog.adminui/Views/Shared/ArticlePartial.cshtml
@model ArticleViewModel

@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common

@using Microsoft.AspNetCore.Routing


<table class="table">
    <thead>
        <tr>
            <th scope="col"><i class="fa fa-image"></i> Cover</th>
            <th scope="col">Category</th>
            <th scope="col">SubCategory</th>
            <th scope="col">Subject</th>
            <th scope="col">Save Date</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.Articles)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.CoverPhoto))
                    {
                        <img src="~/images/@item.CoverPhoto" alt="Cover" height="30px;" width="30px;" class="img-thumbnail"/>
                    }
                </td>
                <td>@item.SubCategory.Category.Detail</td>
                <td>@item.SubCategory.Detail</td>
                <td>@item.Subject</td>
                <td>@(item.SaveDate!=null?Convert.ToDateTime(item.SaveDate).ToString("yyyy-MM-dd HH:mm:ss"):"-")</td>
                <td>
                    @if (item.IsActive)
                    {
                        <span class="label label-inline label-light-success font-weight-bold">Aktif</span>
                    }
                    else
                    {
                        <span class="label label-inline label-light-danger font-weight-bold">Pasif</span>
                    }
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                        <div class="dropdown-menu">
                            <button class="dropdown-item update" name="@item.ArticleId">Update</button>
                            <button class="dropdown-item updateCover" name="@item.ArticleId">Upload Cover</button>
                            <button class="dropdown-item changeStatus" name="@item.ArticleId">Change Status</button>
                        </div>
                    </div>
                </td>
            </tr>

        }

    </tbody>
</table>

@Html.PagedListPager(Model.Articles, page => Url.Action("Articles", "Article", new RouteValueDictionary {
    { "Page", page },
    { "CategoryId", Model.CategoryId },
    { "SubCategoryId", Model.SubCategoryId },
}), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "data" }))

com.course.blog.adminui/Views/Shared/CategoryPartial.cshtml
@model CategoryViewModel

@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common

@using Microsoft.AspNetCore.Routing


<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Category Name</th>
            <th scope="col">Description</th>
            <th scope="col">Save Date</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.Categories)
        {
            <tr>
                <th scope="row">@item.CategoryId</th>
                <td>@item.Detail</td>
                <td>@item.Description</td>
                <td>@(item.SaveDate!=null?Convert.ToDateTime(item.SaveDate).ToString("yyyy-MM-dd HH:mm:ss"):"-")</td>
                <td>
                    @if (item.IsActive)
                    {
                        <span class="label label-inline label-light-success font-weight-bold">Aktif</span>
                    }
                    else
                    {
                        <span class="label label-inline label-light-danger font-weight-bold">Pasif</span>
                    }

                </td>
                <td></td>
            </tr>

        }

    </tbody>
</table>

@Html.PagedListPager(Model.Categories, page => Url.Action("Categories", "Category", new RouteValueDictionary {
    { "Page", page },
}), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "data" }))

com.course.blog.adminui/Views/Shared/SubCategoryPartial.cshtml
@model SubCategoryViewModel

@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common

@using Microsoft.AspNetCore.Routing


<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Category Name</th>
            <th scope="col">SubCategory Name</th>
            <th scope="col">Description</th>
            <th scope="col">Save Date</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.SubCategories)
        {
            <tr>
                <td scope="row">@item.SubCategoryId</td>
                <td>@item.Category.Detail</td>
                <td>@item.Detail</td>
                <td>@item.Description</td>
                <td>@(item.SaveDate!=null?Convert.ToDateTime(item.SaveDate).ToString("yyyy-MM-dd HH:mm:ss"):"-")</td>
                <td>
                    @if (item.IsActive)
                    {
                        <span class="label label-inline label-light-success font-weight-bold">Aktif</span>
                    }
                    else
                    {
                        <span class="label label-inline label-light-danger font-weight-bold">Pasif</span>
                    }

                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                        <div class="dropdown-menu">
                            <button class="dropdown-item update" name="@item.SubCategoryId">Update</button>
                            <button class="dropdown-item changeStatus" name="@item.SubCategoryId">Change Status</button>
                        </div>
                    </div>
                </td>
            </tr>

        }

    </tbody>
</table>

@Html.PagedListPager(Model.SubCategories, page => Url.Action("SubCategories", "SubCategory", new RouteValueDictionary {
    { "Page", page },
    { "CategoryId", Model.CategoryId },
}), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "data" }))